
# frozen_string_literal: true
source 'https://rubygems.org'

gem 'active_model_serializers', '~> 0.8.3'
gem 'api-pagination'
gem 'httparty'
gem 'kaminari'
gem 'migration-export', path: '../../'
gem 'pg'
gem 'rails', '4.2.5.1'
gem 'rails-api'
gem 'spring', group: :development

ruby '2.3.0'
